### ISSUE TITLE
feat(relay): add example

### ISSUE THREAD

**Issue by tarrencev** [pion/ion-sfu#101]
`ion-sfu` supports sfu <> sfu relay. we should add an example.

we can add a gRPC endpoint that can be called to connect to a remote sfu + session which will automatically start relaying the tracks. `ion-avp` does something similar already.

**Comment by obasajujoshua31** [comment]
Implementation plan 


1. update sfu.proto with new rpc
rpc ConnectRemote(stream Signalrequest) returns (stream signalResponse) {}

2. compile the sfu.proto that will generate go stubs and add connectRemote server and client implementation

3. in connectRemote server, I will call Server.signal with the stream coming from connectRemote stream

4. Add examples in the examples directory.

**Comment by tarrencev** [comment]
Awesome! I think this is a solid direction

For the api, I think we can do something like:
```
rpc Relay(RelayRequest) returns (RelayResponse) {}

message Request {
    string sfu = 1; 
    string sid = 2;
}
```

Calling `Relay` will create an `SFUClient` for the given sfu address if one doesn't exist. Then `SFUClient` can join the remote `SFUServer` and begin signaling.
