### ISSUE TITLE
feat(metrics): expose metrics endpoints

### ISSUE THREAD

**Issue by tarrencev** [pion/ion-sfu#110]
for sfu monitoring, we would like to expose metrics endpoints. we can expose these through go apis initially then through gRPC for consumption by prometheus later.

some initial metrics we should support:

- number of sessions
- number of peers
- number of tracks
- peers per session
- tracks per peer
- ice disconnects/failures/closes
- peer bandwidth metrics
- nack/jitter buffer metrics (drops/misses/ect)
- error counts

let me know if you have any other ideas/suggestions

@steebchen @leewardbound @decanus

**Comment by tarrencev** [comment]
i think for errors the best approach is to just scrape logs?

**Comment by jinleileiking** [comment]
prometheus is  a good solution.
