### ISSUE TITLE
Cut video track sdp as need

### ISSUE THREAD

**Issue by adwpc** [pion/ion-sfu#120]
## Summary
The sfu sdp of each video track has dozens of lines;
It will waste a lot of traffic when renegotiation(for example: a 50 person room)
Most 'a=' lines are useless for video track because one video track only need one codec
It's hard to debug/metric/log for sfu

## Motivation

- [ ] SFU choose these video track codec and params(rtpmap fmtp rtcp-fb etc..)
- [ ] Cut the useless sdp lines make debug/metric/log easy and save traffic when renegotiation

**Comment by tarrencev** [comment]
I would love to see some data on sdp size increase. I suspect with gzip the repetitions won't really add much over the wire. Parsing will be slower though. Either way, we should optimize at some point

**Comment by adwpc** [comment]
As we discussed , we should cut sdp in sdk-side.

**Comment by adwpc** [comment]
this feature also helpful with IOS and Firefox
https://github.com/pion/ion/commit/ce0ff4212255966c0496e1660275ab30708506bd#diff-bc62f222cf631aedf64b8e861873308cf293706fa175a3490a3b626dfb915223R18
