### ISSUE TITLE
MediaStreamTrack.enabled = false, NACKS

### ISSUE THREAD

**Issue by OrlandoCo** [pion/ion-sfu#122]
### Your environment.
  - Version: *LATEST*
  - Browser: *LATEST*
### What did you do?

When video track is disabled, the SFU starts forwarding NACKS continuously.

### What did you expect?

No NACKS messages.

### What happened?

Maybe it's possible to add a parameter to let know pion that a track it's going to be disabled, or limit rate the NACKS

**Comment by tarrencev** [comment]
interesting. i'm not sure what the correct solution is here. how does chrome p2p handle it?

**Comment by adwpc** [comment]
Not sure how libwebrtc did.Maybe sfu can add some signal like：mute/unmute

**Comment by OrlandoCo** [comment]
I prepared this small fiddle https://jsfiddle.net/0kapg6wh/7/, so it's just peer to peer, when video is disabled, you can se that no nack  packages are sent.

![image](https://user-images.githubusercontent.com/16469340/92424923-4fb00b80-f14b-11ea-9da6-7dd5f4ece2a3.png)

**Comment by OrlandoCo** [comment]
Since the disabled tracks sends empty packets I think that in the ```Buffer.Push``` method if an empty packet is detected we should clear the buffer and return until a none empty package is recieved.

The buffer must be cleared because, the SFU will keep sending nack after the track is enabled, also make a flag to pause remb and pli loops.

**Comment by adwpc** [comment]
@OrlandoCo 
Nice find!
That would be aswome if you can help with a PR!

**Comment by OrlandoCo** [comment]
Since the disabled video track doesn't send empty payload but full black pixel frame, the size of the packet will change depending of many factors but will be a fraction of a normal packet, so we can take 3 approachs:

1. Decode the frame to see if it's full black, this is a very expensive way.
2. Make a threshold for an empty packet like some % of a normal packet.
3. Call a method to let know SFU that a track is going to be disabled/enabled

**Comment by tarrencev** [comment]
I wonder which approach libwebrtc takes?

I would prefer not to have to manually signal mutes. Then we may as well remove/add the track.

I think 2 works well for now

**Comment by OrlandoCo** [comment]
Investigating more, I found that the root of the NACKS was because packets were being cleaned before they could be read, the reason is that when video is muted, the packages per second drops to 15.

The quickest solution is to increase the buffertime, and the nacks are gone. I will to investigate better the best default buffertime value to prevent this problem.

**Comment by tarrencev** [comment]
@OrlandoCo Interesting find! Please let me know where you land on this. It might make sense to dynamically adjust buffer time based on packet frequency

**Comment by OrlandoCo** [comment]
@tarrencev I think that an easy solution is to move the cleaner after the nack pair calculation, in that way it's not necessary to dynamycally adjust the buffer, and the extra packets are negligible.

```go
	if b.lastPushSN-b.lastNackSN >= maxNackLostSize {
		// calc [lastNackSN, lastpush-8] if has keyframe
		nackPair, lostPkt := b.GetNackPair(b.pktBuffer, b.lastNackSN, b.lastPushSN)
	        // clear old packet by timestamp
	        b.clearOldPkt(p.Timestamp, p.SequenceNumber)
		b.lastNackSN = b.lastPushSN
		log.Tracef("b.lastNackSN=%v, b.lastPushSN=%v, lostPkt=%v, nackPair=%v", b.lastNackSN, b.lastPushSN, lostPkt, nackPair)
		if lostPkt > 0 {
			b.lostPkt += lostPkt
			nack := &rtcp.TransportLayerNack{
				//origin ssrc
				// SenderSSRC: b.ssrc,
				MediaSSRC: b.ssrc,
				Nacks: []rtcp.NackPair{
					nackPair,
				},
			}
			b.rtcpCh <- nack
		}
	}

```

**Comment by tarrencev** [comment]
sounds good! would you mind contributing the fix?
