### ISSUE TITLE
One client only create one PC(udp connection to sfu) for exchanging many other clients media data.

### ISSUE THREAD

**Issue by jinleileiking** [pion/ion-sfu#131]
## Summary

One client only create one PC(udp connection to sfu) for exchanging many other clients media data.

## Motivation

In current design. Let us think one will communicate with another( like 11 live chat room).

A -- SFU --- B

A pub B sub :         A ----PC1----> SFU  -----PC2 --->B
B pub A sub:          A ----PC3--->  SFU ----PC4---> B

I will setup 2 udp connections (PC)  from A to SFU. If have more clients, the connection will be more.

One solution is like:        A ----PC(SSRC-1-A SSRC-1-V SSRC-3-A  SSRC-3-V) ---- SFU

**Comment by tarrencev** [comment]
this is the current design. only single pc is used per session per sfu

**Comment by tarrencev** [comment]
closing since as i understand your issue, this is already the behavior. feel free to reopen if i am misunderstanding!

**Comment by jinleileiking** [comment]
Thanks.
