### ISSUE TITLE
flakey test: TestPeerRemovesRouterWhenRemoteRemovesTrack

### ISSUE THREAD

**Issue by tarrencev** [pion/ion-sfu#143]
![image](https://user-images.githubusercontent.com/4740651/92839621-31961580-f3ae-11ea-882c-8f953881388a.png)

**Comment by OrlandoCo** [comment]
I think since the onRemoveTrack method is async, sometimes it fires after the GetRouter method call, adding a small sleep makes the test succesd all the time.

**Comment by tarrencev** [comment]
Nice! What other hidden secrets are you waiting for me to uncover? 😛
