### ISSUE TITLE
 Incoming unhandled RTP ssrc

### ISSUE THREAD

**Issue by tarrencev** [pion/ion-sfu#144]
I see this error pops up now and again:

```
pc ERROR: 2020/09/11 01:42:44 Incoming unhandled RTP ssrc(2854263694), OnTrack will not be fired. single media section has an explicit SSRC
```

**Comment by adwpc** [comment]
Myabe rtx error which pion not supported，can find more info in sdp

**Comment by OrlandoCo** [comment]
This error it's from [peerconnection](https://github.com/pion/webrtc/blob/c2ed6ee8350dff4b38ef2409a8d6619f6edfe9d7/peerconnection.go#L1307) and [here](https://github.com/pion/webrtc/blob/c2ed6ee8350dff4b38ef2409a8d6619f6edfe9d7/peerconnection.go#L1226), it's seems that pion expect that when it's only a single media in the SDP there must not be a explicit SSRC. I this error generated from a particular test?

**Comment by tarrencev** [comment]
it is generated intermittently, which makes me think it is a race condition

**Comment by OrlandoCo** [comment]
> it is generated intermittently, which makes me think it is a race condition

This must be called only on SetRemoteDescription, since it's intermittently maybe is on negotiation, something mus be wrong with the generated SDP, maybe log the SDP when this error is fired can help.

**Comment by tarrencev** [comment]
I sometimes get this error on the client which i think might be related

![image](https://user-images.githubusercontent.com/4740651/92934131-1f02f700-f415-11ea-8675-4a62252acf96.png)

**Comment by tarrencev** [comment]
here is an sdp diff of two clients to the sfu that received an offer when a 3rd joined:

https://www.diffchecker.com/esVPVDm0

you can see in the one of the left that there is a missing `mid` on line 127

**Comment by OrlandoCo** [comment]
This is very weird because the errors are not related, the SFU erros it's when the SDP just contain a single ```M-Line``` but with a ```a=ssrc``` tag, and your front end error is a clear missing of the token in the ```a=mid:xxx```  tag, but it seems that pion will not check for that error.

So something is messing up the SDP... does yor front end is munging the SDP, maybe there is a bug in the parsing library??.

**Comment by tarrencev** [comment]
closing since i havent seen this in awhile. i think it was related to RTP arriving before negotiation is complete
