### ISSUE TITLE
pub/sub streamer

### ISSUE THREAD

**Issue by yarekc** [pion/ion-sfu#164]
hi,
I would like to contribute with my suggestion: 
I tested many SFU solutions: mediasoup2 and 3, janus, licode, red5pro, jitsi, kurento and they are appear to me too complex compared to a simple old RTMP stream: 
You publish a stream streamid and you play the stream streamid 
In fact all done with 2 functions

- publishStream(videoDomElement, streamid);
- playStream(videoDomElement, streamid);

May I suggest to use that paradigm for end user developer ? 
(hiding all webrtc protocol exchanging)

That would be really simple selective forward unit: I publish streamid and I decide what streamid I want to play

Regards

**Comment by OrlandoCo** [comment]
This can be totally done, but this should be suggested in the SDK's you are interested in, if you take a look in the [JS SDK repo](https://github.com/pion/ion-sdk-js) you can see that it's not as complex as kurento,janus or mediasoup.
