### ISSUE TITLE
We should simplify how we are closing senders. It should be triggered by the `p.pc.RemoveTrack` call, rather than the other way around.

### ISSUE THREAD

**Issue by tarrencev** [pion/ion-sfu#177]
> We should simplify how we are closing senders. It should be triggered by the `p.pc.RemoveTrack` call, rather than the other way around.

According to this [comit](https://github.com/pion/webrtc/pull/1140) from Pion/Webrtc we should close the sender when a `io.EOF` it's recieved from the `webrtc.Track#Read()`, Currently now we are closing senders only on peer disconnecting /failing

_Originally posted by @OrlandoCo in https://github.com/pion/ion-sfu/pull/176#issuecomment-693529630_

**Comment by OrlandoCo** [comment]
@tarrencev can you assign this to me?
