### ISSUE TITLE
Settings IP for sdp candidate

### ISSUE THREAD

**Issue by lxShaDoWxl** [pion/ion-sfu#182]
If you use Docker, the IP of the container is added to the sdp and clients located on the host's local network cannot connect. Can you add to the settings so that you can specify which other IP addresses to add to the sdp? otherwise it turns out that the container will only work for the local host

**Comment by tarrencev** [comment]
Hmm i havent seen this issue and run `ion-sfu` in a container locally. Are you opening the containers UDP port range?

**Comment by lxShaDoWxl** [comment]
If you run it in a container and try to connect via a local network from another device the sdp does not have the IP host on which the container is running
Example:
Local IP 192.168.0.2
Container IP 172.25.0.174
if connect from 192.168.0.3 then the sdp address equal 172.25.0.174

**Comment by lxShaDoWxl** [comment]
Example settings in janus-gateway
https://github.com/meetecho/janus-gateway/blob/master/conf/janus.jcfg.sample.in#L267

**Comment by tarrencev** [comment]
gotcha! if youd like, you can create a PR with this functionality

**Comment by tarrencev** [comment]
@lxShaDoWxl please let me know if #184 solves your issue. thanks for surfacing this!

**Comment by lxShaDoWxl** [comment]
Yes, this solves the problem. Thanks!
