### ISSUE TITLE
Add / Remove Tracks

### ISSUE THREAD

**Issue by decanus** [pion/ion-sfu#198]
## Summary

A feature to be able to add and remove sending tracks for specific peers.

## Motivation

One of the features I require for my use case, is that the ion-sfu server can remove sending tracks for specific users. I need this because an admin user in my application should be able to mute and unmute other members at will, which is currently not possible.

I am opening an issue as requested by @OrlandoCo. CC: @tarrencev whom I have discussed this issue with extensively.

## Additional context

- https://github.com/pion/ion-sfu/pull/196

**Comment by tarrencev** [comment]
I think we could include this as part of layer switching. it will be necessary to support use cases where participants are off screen too. We could support a "layer" where the track is removed/muted. Conceptually I think it would be nice to align these features. What do you think @OrlandoCo

**Comment by OrlandoCo** [comment]
I think that this can be done without adding more methods:

1. Remove a track, it requires to use an external signaling or datachannels to communicate with peer, it can confirm that track is removed on negotiation on client side and the ```onremovetrack``` event from stream. 
2. Mute a track, this requires also to signal the peer to mute his track, a muted track can be confirmed by bandwidth consumption on peer.

@tarrencev Yes we can add a zero layer for all simulcast tracks.

**Comment by tarrencev** [comment]
Yup it is definitely possible already with signaling to terminate at the pub. For sfu termination, zero layer would work nicely. I think it would be good to support for all tracks, not just simulcast (audio + SVC too)
