### ISSUE TITLE
json.Unmarshall error while using sdp from browser for pub-from-browser example

### ISSUE THREAD

**Issue by Wrufesh** [pion/ion-sfu#20]
### Your environment.
  - Version: *0dd6b83fa52f9726695a59e4699537da9e6becbb*
  - OS: *Arch Linux*
  - Browser: *Google Chrome Version 81.0.4044.129 (Official Build) (64-bit)*

### What did you do?
I was following the examples code for **pub-from-browser**

I copied the **base64 sdp** from from top text are of **jsfiddle** in expample **README.md**

Pasted sdp to sdp.txt
then,

`cat sdp.txt | go run pub_from_browser/main.go`

### What did you expect?
I expected to get an another sdp to paste in jsfiddle and start the session

### What happened?
Then I get following error traceback:

```
[wrocket@wrocket-pc pub-from-browser]$ cat sdp.txt | go run main.go

panic: illegal base64 data at input byte 1

goroutine 1 [running]:
github.com/pion/ion-sfu/examples/internal/signal.Decode(0xc000016a00, 0x2124, 0x94e3a0, 0xc000074af0)
	/home/wrocket/git/ion-sfu/examples/internal/signal/signal.go:74 +0xbf
main.main()
	/home/wrocket/git/ion-sfu/examples/pub-from-browser/main.go:30 +0x20d
exit status 2
```

I found the **sdp value in json is string** and `Sdp` in `SDPDescription` struct  in proto3 is []byte.
And because of it we are having issue in `json.Unmarshall `

**Comment by tarrencev** [comment]
@Wrufesh thanks for reporting. this same patch needs to be applied to this example: https://github.com/pion/ion-sfu/pull/17/files

if you wouldn't mind opening a PR to do that, it would be greatly appreciated!

**Comment by Wrufesh** [comment]
I am new to golang but I would love to try. :)
