### ISSUE TITLE
no plan b fallback as of #84

### ISSUE THREAD

**Issue by tomsun** [pion/ion-sfu#212]
### Your environment.
  - Version: 28bb6372b2209ec2952b4dbdd53b0c56902664bf
  - Browser: iOS / XCode / Flutter

### What did you do?
Tried using ion-sfu (standalone) with [flutter_webrtc](https://github.com/flutter-webrtc/flutter-webrtc) (0.2.8 and 0.3.3)

### What did you expect?
A successful connection (since https://github.com/pion/ion works just fine with https://github.com/pion/ion-sdk-flutter which uses flutter_webrtc)

### What happened?
[offer SDP semantics does not match configuration](https://github.com/pion/webrtc/blob/f3d42e01203cc902ab6d6902cffade47a4a0394b/errors.go#L85)

Reason: #84 disabled the plan b fallback https://github.com/pion/ion-sfu/pull/84/files#diff-dd4ded5678806fb0c41b7ef5413f0dfdL40 and flutter_webrtc seems to use plan b currently

Was this a desired change?

(@tarrencev describes that commit with "update confs", so not entirely clear to me whether there was intent to drop the plan b fallback or not)

(There is a recent WiP PR that might solve this scenario by moving flutter_webrtc to unified plan https://github.com/flutter-webrtc/flutter-webrtc/pull/359 - but the problem scope isn't necessarily constrained to that... or is plan-b dead and long gone everywhere except in flutter_webrtc?)

**Comment by tarrencev** [comment]
We plan to allow for full configuration of the webrtc SettingEngine. This is described in #192. You're welcome to open a PR to allow configuration of `SDPSemantics`

**Comment by cloudwebrtc** [comment]
@tomsun `flutter-webrtc 0.4.0` now support unified-plan.

**Comment by tarrencev** [comment]
this is now supported
