### ISSUE TITLE
Repository: ReadMe of the examples leads to 404

### ISSUE THREAD

**Issue by miseifert** [pion/ion-sfu#216]
I wanted to checkout the example code on the repository, however every link on the https://github.com/pion/ion-sfu/tree/master/examples result in 404s.

After a bit of searching I found that these probably have been moved to https://github.com/pion/ion-examples/tree/master/ion-sfu.

I think it would be great if you could update the links or just redirect from the ReadMe to the other repository.

Thanks in advance.

**Comment by TannerGabriel** [comment]
I also noticed that! Should hopefully be fixed after this PR.

**Comment by miseifert** [comment]
@TannerGabriel Thank you 👍
