### ISSUE TITLE
Main ReadMe: Question about port for JSONrpc docker

### ISSUE THREAD

**Issue by miseifert** [pion/ion-sfu#254]
The current readme says one should use

```
docker run -p 50051:50051 -p 5000-5020:5000-5020/udp pionwebrtc/ion-sfu:latest-jsonrpc
```

However when I start this docker container it says (on the command line) that it's listening on port 7000? Shouldn't the exposed port be 7000 then?

E.g.

```
docker run -p 7000:7000 -p 5000-5020:5000-5020/udp pionwebrtc/ion-sfu:latest-jsonrpc
           ^^^^^^^^^^^^
```

**Comment by tarrencev** [comment]
yes you are right. the readme should be updated. sorry about that

**Comment by tarrencev** [comment]
updated :)

**Comment by miseifert** [comment]
Awesome! Thank you for the fast replay and the fix 👍
