### ISSUE TITLE
Examples use track.onremovetrack but should use stream.onremovetrack

### ISSUE THREAD

**Issue by tryge** [pion/ion-sfu#344]
### Your environment.
  - Version: macOS 10.15.7
  - Browser: Firefox 84.0
  - Other Information - fixed by changing to stream.onremovetrack and checking event for track kind before removing the video element (because stream.onremovetrack is called twice)

### What did you do?
Tested with pubusbtest, open two browser tabs, start publishing on both, close a browser tab and the remotes video element belonging to the closed browser tab is frozen and not removed.

### What did you expect?

The video element should be removed correctly when the other party leaves the page or closes the browser tab.

### What happened?

The video element remains on the page and shows a frozen picture.

**Comment by tarrencev** [comment]
@tryge thank you for this issue! the pubsub example is not very robust, it is designed to be a minimal example of something that works. that said, your suggestion makes sense and we'd appreciate a contribution to improve the example!
