### ISSUE TITLE
Crash: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by tmiv** [pion/ion-sfu#363]
### Your environment.
  - Version: 3dbe475212b0022669e3c2ebf3812d2ec19526b4
  - Browser:  Chrome Version 87.0.4280.88 (Official Build) (x86_64) & Chrome Version 87.0.4280.101 (Android)
  
### What did you do?
Running normally with two clients connected in one session. Then a crash occurred with this call stack:

```
Jan 02 09:52:43 nivelumi-dev startup.sh[5798]: panic: runtime error: slice bounds out of range [36502:36500]
Jan 02 09:52:43 nivelumi-dev startup.sh[5798]: goroutine 432 [running]:
Jan 02 09:52:43 nivelumi-dev startup.sh[5798]: github.com/pion/ion-sfu/pkg/buffer.(*Bucket).push(...)
Jan 02 09:52:43 nivelumi-dev startup.sh[5798]:         /srv/ion-sfu/pkg/buffer/bucket.go:79
Jan 02 09:52:43 nivelumi-dev startup.sh[5798]: github.com/pion/ion-sfu/pkg/buffer.(*Bucket).addPacket(0xc000064180, 0xc000972000, 0x47, 0x2000, 0x14ade, 0x51679f, 0xa, 0xc0002754a0)
Jan 02 09:52:43 nivelumi-dev startup.sh[5798]:         /srv/ion-sfu/pkg/buffer/bucket.go:58 +0x2f7
Jan 02 09:52:43 nivelumi-dev startup.sh[5798]: github.com/pion/ion-sfu/pkg/buffer.(*Buffer).calc(0xc0002265a0, 0xc000972000, 0x47, 0x2000, 0x1656618a41205d0d)
Jan 02 09:52:43 nivelumi-dev startup.sh[5798]:         /srv/ion-sfu/pkg/buffer/buffer.go:250 +0x105
Jan 02 09:52:43 nivelumi-dev startup.sh[5798]: github.com/pion/ion-sfu/pkg/buffer.(*Buffer).Write(0xc0002265a0, 0xc000972000, 0x47, 0x2000, 0x0, 0x0, 0x0)
Jan 02 09:52:43 nivelumi-dev startup.sh[5798]:         /srv/ion-sfu/pkg/buffer/buffer.go:184 +0x11d
Jan 02 09:52:43 nivelumi-dev startup.sh[5798]: github.com/pion/srtp/v2.(*ReadStreamSRTP).write(0xc000735800, 0xc000972000, 0x47, 0x2000, 0xc000972000, 0x51, 0x2000)
Jan 02 09:52:43 nivelumi-dev startup.sh[5798]:         /root/go/pkg/mod/github.com/pion/srtp/v2@v2.0.0-rc.3.0.20201219001609-888371fe3846/stream_srtp.go:63 +0x56
Jan 02 09:52:43 nivelumi-dev startup.sh[5798]: github.com/pion/srtp/v2.(*SessionSRTP).decrypt(0xc0000ca4d0, 0xc000972000, 0x51, 0x2000, 0x51, 0x0)
Jan 02 09:52:43 nivelumi-dev startup.sh[5798]:         /root/go/pkg/mod/github.com/pion/srtp/v2@v2.0.0-rc.3.0.20201219001609-888371fe3846/session_srtp.go:160 +0x1a8
Jan 02 09:52:43 nivelumi-dev startup.sh[5798]: github.com/pion/srtp/v2.(*session).start.func1(0xc0000ca4d0, 0xc0004afd80, 0xc66740, 0xc0000ca4d0)
Jan 02 09:52:43 nivelumi-dev startup.sh[5798]:         /root/go/pkg/mod/github.com/pion/srtp/v2@v2.0.0-rc.3.0.20201219001609-888371fe3846/session.go:141 +0x12d
Jan 02 09:52:43 nivelumi-dev startup.sh[5798]: created by github.com/pion/srtp/v2.(*session).start
Jan 02 09:52:43 nivelumi-dev startup.sh[5798]:         /root/go/pkg/mod/github.com/pion/srtp/v2@v2.0.0-rc.3.0.20201219001609-888371fe3846/session.go:120 +0x226
```
This has only occurred once in a lot of testing.

**Comment by OrlandoCo** [comment]
This is a really strange issue I could not understand how it could happen, I will leave it open until we find the reason

**Comment by tmiv** [comment]
I agree checked the math. It seems to work out, but I did notice you changed https://github.com/pion/ion-sfu/blob/457db65ce7b4f056f70e9f8a2202bd8a13dbd101/pkg/buffer/bucket.go#L26 maybe that will fix it. I thought that signed integer division should always truncate toward 0, but maybe I'm wrong.

The only other way I thought it could happen is that if two addPacket / push operations from two threads hit the same bucket at similar times, there could be a conflict. I have very little insight into how this code is utilized in the system or if it is possible that a multithreading issue could be the culprit.

**Comment by tmiv** [comment]
I'm now on 7ae23aead5deebd45ca99d64fcccde4ddee7b297 and have a new crash with a new call stack that is most likely related
```
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: panic: runtime error: index out of range [1] with length 0
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: goroutine 591 [running]:
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: encoding/binary.bigEndian.PutUint16(...)
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /snap/go/6745/src/encoding/binary/binary.go:106
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/ion-sfu/pkg/buffer.(*Bucket).push(...)
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /srv/ion-sfu/pkg/buffer/bucket.go:78
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/ion-sfu/pkg/buffer.(*Bucket).addPacket(0xc0003cb340, 0xc000fea000, 0x2f, 0x2000, 0x1000000017ce4, 0x56f63f, 0xa, 0xc000239970)
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /srv/ion-sfu/pkg/buffer/bucket.go:59 +0x305
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/ion-sfu/pkg/buffer.(*Buffer).calc(0xc0004ac960, 0xc000fea000, 0x2f, 0x2000, 0x16579225cfa7553e)
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /srv/ion-sfu/pkg/buffer/buffer.go:259 +0x105
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/ion-sfu/pkg/buffer.(*Buffer).Write(0xc0004ac960, 0xc000fea000, 0x2f, 0x2000, 0x0, 0x0, 0x0)
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /srv/ion-sfu/pkg/buffer/buffer.go:193 +0x11d
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/srtp/v2.(*ReadStreamSRTP).write(0xc000fddf80, 0xc000fea000, 0x2f, 0x2000, 0xc000fea000, 0x39, 0x2000)
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /home/tmiv74_gmail_com/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/stream_srtp.go:64 +0x56
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/srtp/v2.(*SessionSRTP).decrypt(0xc000a6e000, 0xc000fea000, 0x39, 0x2000, 0x39, 0x0)
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /home/tmiv74_gmail_com/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/session_srtp.go:165 +0x1a8
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/srtp/v2.(*session).start.func1(0xc000a6e000, 0xc0003ac2c0, 0xdebe00, 0xc000a6e000)
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /home/tmiv74_gmail_com/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/session.go:141 +0x12d
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: created by github.com/pion/srtp/v2.(*session).start
Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /home/tmiv74_gmail_com/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/session.go:120 +0x226
```

**Comment by OrlandoCo** [comment]
> I agree checked the math. It seems to work out, but I did notice you changed
> 
> https://github.com/pion/ion-sfu/blob/457db65ce7b4f056f70e9f8a2202bd8a13dbd101/pkg/buffer/bucket.go#L26
> 
> maybe that will fix it. I thought that signed integer division should always truncate toward 0, but maybe I'm wrong.
> The only other way I thought it could happen is that if two addPacket / push operations from two threads hit the same bucket at similar times, there could be a conflict. I have very little insight into how this code is utilized in the system or if it is possible that a multithreading issue could be the culprit.

All the bucket methods are protected by a lock, so only one thread at a time can modify it.

**Comment by OrlandoCo** [comment]
> I'm now on [7ae23ae](https://github.com/pion/ion-sfu/commit/7ae23aead5deebd45ca99d64fcccde4ddee7b297) and have a new crash with a new call stack that is most likely related
> 
> ```
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: panic: runtime error: index out of range [1] with length 0
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: goroutine 591 [running]:
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: encoding/binary.bigEndian.PutUint16(...)
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /snap/go/6745/src/encoding/binary/binary.go:106
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/ion-sfu/pkg/buffer.(*Bucket).push(...)
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /srv/ion-sfu/pkg/buffer/bucket.go:78
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/ion-sfu/pkg/buffer.(*Bucket).addPacket(0xc0003cb340, 0xc000fea000, 0x2f, 0x2000, 0x1000000017ce4, 0x56f63f, 0xa, 0xc000239970)
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /srv/ion-sfu/pkg/buffer/bucket.go:59 +0x305
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/ion-sfu/pkg/buffer.(*Buffer).calc(0xc0004ac960, 0xc000fea000, 0x2f, 0x2000, 0x16579225cfa7553e)
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /srv/ion-sfu/pkg/buffer/buffer.go:259 +0x105
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/ion-sfu/pkg/buffer.(*Buffer).Write(0xc0004ac960, 0xc000fea000, 0x2f, 0x2000, 0x0, 0x0, 0x0)
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /srv/ion-sfu/pkg/buffer/buffer.go:193 +0x11d
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/srtp/v2.(*ReadStreamSRTP).write(0xc000fddf80, 0xc000fea000, 0x2f, 0x2000, 0xc000fea000, 0x39, 0x2000)
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /home/tmiv74_gmail_com/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/stream_srtp.go:64 +0x56
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/srtp/v2.(*SessionSRTP).decrypt(0xc000a6e000, 0xc000fea000, 0x39, 0x2000, 0x39, 0x0)
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /home/tmiv74_gmail_com/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/session_srtp.go:165 +0x1a8
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/srtp/v2.(*session).start.func1(0xc000a6e000, 0xc0003ac2c0, 0xdebe00, 0xc000a6e000)
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /home/tmiv74_gmail_com/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/session.go:141 +0x12d
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: created by github.com/pion/srtp/v2.(*session).start
> Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /home/tmiv74_gmail_com/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/session.go:120 +0x226
> ```

Could you tell me how do you get this error?, Im not sure how the buffer could be 0 size since initialized on start

**Comment by tmiv** [comment]
> > I'm now on [7ae23ae](https://github.com/pion/ion-sfu/commit/7ae23aead5deebd45ca99d64fcccde4ddee7b297) and have a new crash with a new call stack that is most likely related
> > ```
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: panic: runtime error: index out of range [1] with length 0
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: goroutine 591 [running]:
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: encoding/binary.bigEndian.PutUint16(...)
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /snap/go/6745/src/encoding/binary/binary.go:106
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/ion-sfu/pkg/buffer.(*Bucket).push(...)
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /srv/ion-sfu/pkg/buffer/bucket.go:78
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/ion-sfu/pkg/buffer.(*Bucket).addPacket(0xc0003cb340, 0xc000fea000, 0x2f, 0x2000, 0x1000000017ce4, 0x56f63f, 0xa, 0xc000239970)
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /srv/ion-sfu/pkg/buffer/bucket.go:59 +0x305
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/ion-sfu/pkg/buffer.(*Buffer).calc(0xc0004ac960, 0xc000fea000, 0x2f, 0x2000, 0x16579225cfa7553e)
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /srv/ion-sfu/pkg/buffer/buffer.go:259 +0x105
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/ion-sfu/pkg/buffer.(*Buffer).Write(0xc0004ac960, 0xc000fea000, 0x2f, 0x2000, 0x0, 0x0, 0x0)
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /srv/ion-sfu/pkg/buffer/buffer.go:193 +0x11d
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/srtp/v2.(*ReadStreamSRTP).write(0xc000fddf80, 0xc000fea000, 0x2f, 0x2000, 0xc000fea000, 0x39, 0x2000)
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /home/tmiv74_gmail_com/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/stream_srtp.go:64 +0x56
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/srtp/v2.(*SessionSRTP).decrypt(0xc000a6e000, 0xc000fea000, 0x39, 0x2000, 0x39, 0x0)
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /home/tmiv74_gmail_com/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/session_srtp.go:165 +0x1a8
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: github.com/pion/srtp/v2.(*session).start.func1(0xc000a6e000, 0xc0003ac2c0, 0xdebe00, 0xc000a6e000)
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /home/tmiv74_gmail_com/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/session.go:141 +0x12d
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]: created by github.com/pion/srtp/v2.(*session).start
> > Jan 06 06:54:42 nivelumi-dev startup.sh[3105]:         /home/tmiv74_gmail_com/go/pkg/mod/github.com/pion/srtp/v2@v2.0.1/session.go:120 +0x226
> > ```
> 
> Could you tell me how do you get this error?, Im not sure how the buffer could be 0 size since initialized on start

I think it's saying the packet size is 0 there.

**Comment by OrlandoCo** [comment]
No, since the error is in this line:
```go
binary.BigEndian.PutUint16(b.buf[b.step*maxPktSize:], uint16(len(pkt)))
```
You can get the len of an empty packet, but the out of range comes from the buffer

**Comment by tmiv** [comment]
> No, since the error is in this line:
> 
> ```go
> binary.BigEndian.PutUint16(b.buf[b.step*maxPktSize:], uint16(len(pkt)))
> ```
> 
> You can get the len of an empty packet, but the out of range comes from the buffer

Sorry. I misspoke. I corrected my previous reply.

**Comment by OrlandoCo** [comment]
does you clients are browsers? Im asking because this may be related to SSRC collision

**Comment by tmiv** [comment]
Yes the browser notation above still holds.

**Comment by OrlandoCo** [comment]
The latest push should fix this issue, I will leave this open for some days

**Comment by OrlandoCo** [comment]
@tmiv have you got this issue agian, I think it's safe to close for now?

**Comment by adwpc** [comment]
close，please reopen if you got this issue again
