### ISSUE TITLE
Data channel Middleware

### ISSUE THREAD

**Issue by tarrencev** [pion/ion-sfu#365]
Right now we support data channel fanout. It would be great to support a middleware interface for processing data channel content. This will allow for more complex data channel usage (i.e. processing inputs before forwarding to subs)

**Comment by tmiv** [comment]
This would be an awesome feature as right now I have a whole separate system for processing data channel from clients and sending back results.

**Comment by tarrencev** [comment]
@tmiv awesome. do you have any ideas around a good interface? my intuition would be to do something similar to typical http middleware. it would be cool if it were modular enough for people to build reusable middlewares. would love for someone to take the lead here if you're interested :)

**Comment by decanus** [comment]
I think a nice way to do it would be to expose the data channel on the peers, and then additionally add an `onMessage` function or something.

Someone could then store peers and do any custom sending in the onMessage function.

**Comment by tmiv** [comment]
I was thinking it would be nice to have them implemented as plugins. That way the sfu could load them at will and they would be very modular. They could be configured in the config.toml where a data channel label would trigger a plugin to load.  Then all incoming messages would be passed to the plugin and the plugin could generate back messages to all or any of the subscriber clients in the session after processing or even at their own pace.

The problem with this idea is that golang plugins don't work in windows. Not sure if the project would be comfortable with that.

**Comment by tarrencev** [comment]
I dont have experience with go plugins specifically but I do think a pluggable middleware approach makes most sense. It sounds like we are discussing two different features here

1) Processing incoming messages on particular data channels. The go plugin approach seems nice since we could make it fully configurable from the toml and people could use middleware with the existing docker images. I'm not sure if this is a requirement though and I would be ok with having people import and extend the sfu for more advanced functionality. 

2) Sending messages in data channels that originate from the sfu (I think this is what @decanus is suggesting?). This should be pretty straight forward to enable through sfu api's.

Let me know if i am missing anything.

**Comment by decanus** [comment]
So I actually need both 1 & 2 to be able to update soapbox's sfu. What would work best is if the sfu could receive messages without forwarding them and then send its own messages, at least on my end.

**Comment by tmiv** [comment]
I think my proposal would cover both cases. [Here is a draft sketch](https://github.com/tmiv/ion-sfu/tree/feature/datachannel_plugins) of what it might look like.

**Comment by OrlandoCo** [comment]
@tmiv Im concerned about plugins, I have seen some issues regarding them and not many people is familiarized with them, what is preventing you for importing the SFU and set the data channel middleware??

**Comment by tmiv** [comment]
You mean building the sfu and middleware into one executable, correct?  Nothing, it's just a matter of configuring it at compile time vs. at runtime. If that's preferable that could be done. Or we could even have the data channel middleware join the sfu as a special kind of publisher / subscriber peer which would make them even more modular. They could even then run on a separate VM.  I'm inclined to agree about plugins, it makes me nervous that they are not supported on windows.

**Comment by adwpc** [comment]
can we close?
