### ISSUE TITLE
(Feat) pacer to sub

### ISSUE THREAD

**Issue by adwpc** [pion/ion-sfu#367]
Seems more smoothly and less nack when using pacing

![CC051019-D834-449B-9E28-640C53A73F5B](https://user-images.githubusercontent.com/12995347/103768594-c0b1f200-505d-11eb-91b0-dbf58e46fa90.jpeg)

**Comment by tarrencev** [comment]
@adwpc could you describe the details? im not sure what pacing is

**Comment by adwpc** [comment]
https://webrtc.googlesource.com/src/+/refs/heads/master/modules/pacing/pacing_controller.h
as a reference
It's just a suggestion. There may be a simple way to implement it
