### ISSUE TITLE
How to extends?

### ISSUE THREAD

**Issue by gfyrag** [pion/ion-sfu#380]
Hello,
I would like to extend this project.
My needs are:
* sharing of information on participants
* access control
* document sharing
* screen sharing

Other than access control, I don't see how to extend the code other than by duplicating and modifying it.

Am I missing something?

Thank you in advance.

**Comment by adwpc** [comment]
We are rewriting ion, which will support your needs.
We also have a old version support these needs. v0.4.6

**Comment by tarrencev** [comment]
closing for now
