### ISSUE TITLE
confused about nackQueue.push

### ISSUE THREAD

**Issue by 63isOK** [pion/ion-sfu#399]
```
func (n *nackQueue) push(sn uint16) {
	var extSN uint32
	if n.maxSN == 0 {
		n.maxSN = sn
	} else if (sn-n.maxSN)&0x8000 == 0 {
		if sn < n.maxSN {
                        // which nack list can come into here?
			n.cycles += maxSN
		}
		n.maxSN = sn
	}
...
}
```

**Comment by OrlandoCo** [comment]
None, but  is important for the nack list to being ordered, so on sequence number rollover we have a nacked sequence number of '65534' and new nacked SN of '3', and '3>65534' thats why we require the cycles.

**Comment by 63isOK** [comment]
@OrlandoCo ,thank you for reply. cycles is useful when packet's id reach 0xffff(M=1).

but i can't find a nack list, which meet "(sn-n.maxSN)&0x8000 == 0" and "sn < n.maxSN" both.

{0x8fff, 0x8003, 0xffff, 0x8001, 0x8002}. n.maxSN is 0xffff when sn is 0x8001. 0x8001-0xffff = 32768 (uint16, 0x8000),
0x8000 & 0x8000 is 1. any packet who's id more than 0x8000 puls 0xfff is more than 0x8000.
so "(sn-n.maxSN)&0x8000 == 0" always false when n.masSN is 0xffff, the cycles is never changed.

where did i go wrong? i need help, I have been so confused these two days that I can't understand.

**Comment by OrlandoCo** [comment]
That condition is for out of order packets, if you already rollover so `n.cycles>0` and you are on sequence number `2` and then is pushed a 65534, then the conditon is met.

This  theorically should not happen since nacks are pushed in order.

**Comment by OrlandoCo** [comment]
@63isOK I think your confusion comes because `maxSN` is not a fixed value, is the current maxSN received by the queue

**Comment by 63isOK** [comment]
@OrlandoCo thank you again. I confuse sn of rtp and rtcp. now,i get it. seq of rtp is 16bits,and seq of rtcp is 15bits.
