### ISSUE TITLE
channel cost lots of cpu

### ISSUE THREAD

**Issue by adwpc** [pion/ion-sfu#420]
## Summary
channel cost lots of cpu

![image](https://user-images.githubusercontent.com/12995347/107498021-387bbb00-6bce-11eb-8572-60c5b18214a8.png)

![image](https://user-images.githubusercontent.com/12995347/107497970-2a2d9f00-6bce-11eb-9eae-c50838a03ae0.png)

## Describe alternatives you've considered

https://github.com/pion/ion-sfu/blob/116cc2c09d60b95e76ea5956f6f5e7add4054a21/pkg/sfu/receiver.go#L270

**Comment by aromancev** [comment]
Same here, the provided example absolutely smashes my MacBook with 8 participants.
[This](https://github.com/pion/example-webrtc-applications/tree/master/sfu-ws), for example, handles 20 participants just fine.

Any update on this?

@OrlandoCo maybe you can help? 🙏

**Comment by davidzhao** [comment]
I think this is an issue with using Go channels. There's quite a bit of overhead associated with it. A post on this: https://syslog.ravelin.com/so-just-how-fast-are-channels-anyway-4c156a407e45

Would it be better to use a `OnPacket()` callback instead? Since `Receiver` is the only consumer of it.

**Comment by adwpc** [comment]
> I think this is an issue with using Go channels. There's quite a bit of overhead associated with it. A post on this: https://syslog.ravelin.com/so-just-how-fast-are-channels-anyway-4c156a407e45
> 
> Would it be better to use a `OnPacket()` callback instead? Since `Receiver` is the only consumer of it.

Thanks for your advice

**Comment by OrlandoCo** [comment]
@aromancev @davidzhao @adwpc Going to work on replacing the go channel, can not use a callback since it will block the buffer.

**Comment by OrlandoCo** [comment]
@adwpc can we close this?

**Comment by adwpc** [comment]
Ofcourse
