### ISSUE TITLE
Single PC per client<->sfu

### ISSUE THREAD

**Issue by tarrencev** [pion/ion-sfu#43]
Instead of having a peer connection per pub/sub, we should have a single pc per client<->sfu and send all tracks over it. that should reduce complexity and port usage

**Comment by Wrufesh** [comment]
Wow sounds great :). That will really scale. Really excited.

**Comment by shvchuk** [comment]
Does it mean that in a simple case of one to one connection all the data/audio/video is going through sfu as well ?

**Comment by tarrencev** [comment]
In that case you don't really need an sfu. You can just do peer to peer

**Comment by shvchuk** [comment]
Yes, exactly. This is what we want to achieve. Currently we are running ion on droplet at DigitalOcean following these instructions  https://github.com/pion/ion/blob/master/docs/production/README.md

I see that ion is routing all connections through SFU regardless the number of users in the room. In case of 2 video participants we would like connection to be peer to peer, when number of participants > 2, then launch SFU routing.

Is there some way to set this? 

We are new to the ion project, sorry if the question is too trivial or "noob" :)

Thanks!
