### ISSUE TITLE
Enable simulcast error

### ISSUE THREAD

**Issue by edwinsyarief** [pion/ion-sfu#431]
### Your environment.
  - Version: Release
  - Client: 1.9.0
  - Environement: Windows
  - Are you using a TURN server? coturn
  - Other Information:
  - [2021-02-19 13:45:55.132] [WARN] [395][downtrack.go][writeSimulcastRTP] => old packet received, can not be sequenced, head: 22689 received: 22682
panic: runtime error: index out of range [14] with length 0

goroutine 223 [running]:
github.com/pion/ion-sfu/pkg/sfu.packetMeta.setVP8PayloadMeta(...)
        C:/sfu/sfu-server/pkg/sfu/sequencer.go:61
github.com/pion/ion-sfu/pkg/sfu.(*DownTrack).writeSimulcastRTP(0xc000615980, 0x0, 0x16650fedb6e549d8, 0x1010002, 0x14, 0xd29c3df158a10060, 0x1744d429, 0x1934dc8, 0x0, 0x0, ...)
        C:/sfu/sfu-server/pkg/sfu/downtrack.go:397 +0xa29
github.com/pion/ion-sfu/pkg/sfu.(*DownTrack).WriteRTP(0xc000615980, 0x0, 0x16650fedb6e549d8, 0x1010002, 0x14, 0xd29c3df158a10060, 0x1744d429, 0x1934dc8, 0x0, 0x0, ...)
        C:/sfu/sfu-server/pkg/sfu/downtrack.go:151 +0x98
github.com/pion/ion-sfu/pkg/sfu.(*WebRTCReceiver).writeRTP(0xc0001981a0, 0x2)
        C:/sfu/sfu-server/pkg/sfu/receiver.go:273 +0x198
created by github.com/pion/ion-sfu/pkg/sfu.(*WebRTCReceiver).AddUpTrack
        C:/sfu/sfu-server/pkg/sfu/receiver.go:114 +0x146

### What did you do?
I'm joining using ion-sdk-js v.1.6.0 with simulcast = true

### What happened?
Error on sfu server

**Comment by tab1293** [comment]
I experienced the same issue. Here was my output (pretty much exactly the same)

```
[2021-02-20 01:53:31.820] [WARN] [395][downtrack.go][writeSimulcastRTP] => old packet received, can not be sequenced, head: 32538 received: 32538
panic: runtime error: index out of range [14] with length 0

goroutine 410 [running]:
github.com/pion/ion-sfu/pkg/sfu.packetMeta.setVP8PayloadMeta(...)
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.0/pkg/sfu/sequencer.go:61
github.com/pion/ion-sfu/pkg/sfu.(*DownTrack).writeSimulcastRTP(0xc00048be00, 0x0, 0x166551d3da0ec37d, 0x10002, 0x14, 0xb2599afd7f1a0060, 0xed79be82, 0x16a6248, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.0/pkg/sfu/downtrack.go:397 +0x2365
github.com/pion/ion-sfu/pkg/sfu.(*DownTrack).WriteRTP(0xc00048be00, 0x0, 0x166551d3da0ec37d, 0x10002, 0x14, 0xb2599afd7f1a0060, 0xed79be82, 0x16a6248, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.0/pkg/sfu/downtrack.go:151 +0x125
github.com/pion/ion-sfu/pkg/sfu.(*WebRTCReceiver).writeRTP(0xc0001a81a0, 0x2)
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.0/pkg/sfu/receiver.go:273 +0x21c
created by github.com/pion/ion-sfu/pkg/sfu.(*WebRTCReceiver).AddUpTrack
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.0/pkg/sfu/receiver.go:114 +0x1a5
```

**Comment by OrlandoCo** [comment]
@edwinsyarief do you know if this issue was during a layer change?

**Comment by edwinsyarief** [comment]
Hi @OrlandoCo ,

> @edwinsyarief do you know if this issue was during a layer change?

I don't know, because, I was testing it with more than 5 participants, then the error occurred. I've tried with the latest commit, the issue still exists.
My goals at least the SFU can handle more than 25 participants.

Please help.

Thank you.

**Comment by OrlandoCo** [comment]
@edwinsyarief This going to be fixed in the next release
