### ISSUE TITLE
Cannot get remote video after a permission dialog was shown

### ISSUE THREAD

**Issue by bskton** [pion/ion-sfu#443]
### Your environment.
  - Version: c52b1cd81c3aa77202338fdbe0872c767946ecf3
  - Client: ion-sdk-js: 1.5.5 (also have the same bug on 1.6.0)
  - Environement: *docker-compose*
  - Are you using a TURN server? *nope*
  - Other Information - Screenshot http://joxi.ru/E2pk8O3fGDnvnm

### What did you do?

1. Clone https://github.com/pion/ion-sfu.git
2. cd ./ion-sfu/examples/pubsubtest
3. docker-compose up
4. Open http://localhost:8000/ in one regular Chrome windows
5. Click Start
6. Open http://localhost:8000/ in a new incognito Chrome windows
7. Click Start
8. Click Allow in a permission dialog.

### What did you expect?
I expected to see local and remote videos in both windows - regular and incognito.

### What happened?
I only saw local videos in both windows - regular and incognito.

**Comment by OrlandoCo** [comment]
This issue happens everytime? never seen that kind of issue in localhost

**Comment by bskton** [comment]
Yes. It happens every time. I reproduced it in Chrome and FF.

**Comment by adwpc** [comment]
pls try new version
