### ISSUE TITLE
Server crash when only 1 client joining the session

### ISSUE THREAD

**Issue by edwinsyarief** [pion/ion-sfu#453]
### Your environment.
  - Version: 1.9.3
  - Client: 1.6.0
  - Environement: Windows
  - Are you using a TURN server? coturn
  - Other Information - [2021-03-03 11:36:08.389] [DEBUG] [48][publisher.go][func1] => Peer cklsw16qg0000vc26qcwlcgsj got remote track id: 7c0edc20-2fa9-498b-a447-ef44f290ac71 mediaSSRC: 449947234 rid :h streamID: 7c97c621-63c1-4ea7-9ccc-2f634fa60c29
[2021-03-03 11:36:08.389] [DEBUG] [180][router.go][AddReceiver] => Setting feedback goog-remb
[2021-03-03 11:36:08.391] [DEBUG] [180][router.go][AddReceiver] => Setting feedback transport-cc
[2021-03-03 11:36:08.392] [DEBUG] [180][router.go][AddReceiver] => Setting feedback nack
[2021-03-03 11:36:08.392] [DEBUG] [180][router.go][AddReceiver] => Setting feedback nack
panic: runtime error: index out of range [1] with length 0

goroutine 274 [running]:
encoding/binary.bigEndian.PutUint16(...)
        c:/go/src/encoding/binary/binary.go:106
github.com/pion/ion-sfu/pkg/buffer.(*Bucket).push(...)
        C:/sfu/sfu-server/pkg/buffer/bucket.go:59
github.com/pion/ion-sfu/pkg/buffer.(*Bucket).AddPacket(0xc0003ceba0, 0xc0003662c0, 0x297, 0x297, 0x17504, 0x0, 0x1ab89a0, 0xc0000cc008, 0x0, 0x19e18ad)
        C:/sfu/sfu-server/pkg/buffer/bucket.go:37 +0x26f
github.com/pion/ion-sfu/pkg/buffer.(*Buffer).calc(0xc000085380, 0xc0003662c0, 0x297, 0x297, 0x1668b7cf870e4f10)
        C:/sfu/sfu-server/pkg/buffer/buffer.go:304 +0x1e5
github.com/pion/ion-sfu/pkg/buffer.(*Buffer).Bind(0xc000085380, 0xc0000671a0, 0x3, 0x4, 0xc000492900, 0x1, 0x1, 0x5dc)
        C:/sfu/sfu-server/pkg/buffer/buffer.go:169 +0x287
github.com/pion/ion-sfu/pkg/sfu.(*router).AddReceiver(0xc000298e60, 0xc000492a20, 0xc0001d0a20, 0x0, 0x0, 0x0)
        C:/sfu/sfu-server/pkg/sfu/router.go:180 +0x498
github.com/pion/ion-sfu/pkg/sfu.NewPublisher.func1(0xc0001d0a20, 0xc000492a20)
        C:/sfu/sfu-server/pkg/sfu/publisher.go:49 +0x24f
created by github.com/pion/webrtc/v3.(*PeerConnection).onTrack
        C:/Users/edwin.syarief/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.10/peerconnection.go:451 +0x11b

### What did you do?
A client just join into the session, then the server crash

### What did you expect?
The server will go fine

### What happened?
The server crashed

**Comment by OrlandoCo** [comment]
@edwinsyarief there was an update on config file, please update it

**Comment by gobwas** [comment]
@OrlandoCo however, it would be nice if server would not panic with such error.

**Comment by OrlandoCo** [comment]
@gobwas you are right, going to fix it
