### ISSUE TITLE
simucast not work sometimes

### ISSUE THREAD

**Issue by adwpc** [pion/ion-sfu#459]
### Your environment.
  - Version: master
  - Client: echotest
  - Environement: macos
  - Are you using a TURN server? no
  - Other Information - 

### What did you do?
simucast not work after i switched some times

**Comment by adwpc** [comment]
seems there are too many old packet in the queue when switch layer
https://github.com/pion/ion-sfu/blob/6b6be58a1c9b684ec66bd3a6839f9d2e0a369f71/pkg/sfu/downtrack.go#L327

**Comment by OrlandoCo** [comment]
@adwpc this may be when a you move to a disabled/non existant layer, so the layer change will block forever. Im going to work on it !

**Comment by OrlandoCo** [comment]
@adwpc can you confirm if this is still an issue with latest release?

**Comment by adwpc** [comment]
@OrlandoCo 
video freezed when i click 'audio mute' immediately after click 'start with simulcast'
