### ISSUE TITLE
pubsubtest via docker(-for-mac)-provided sfu does not work with all browsers

### ISSUE THREAD

**Issue by tomsun** [pion/ion-sfu#465]
### Reproduction steps
1.
```
cd ion-sfu/examples/pubsubtest
docker-compose up
```
2. open http://localhost:8000 in two browser windows
3. click "start" in both windows

### Expected result
Video in the remotes column in both browser windows

### Actual result

- **mbp2019-catalina + firefox 85.0.2**: no remote video + console error: `WebRTC: ICE failed, add a TURN server and see about:webrtc for more details`
- **mbp2019-catalina + chrome 88.0.4324.182**: no remote video + no errors
- **mbp2019-catalina + safari 14.0.2**: no remote video + no errors

- **m1air-bigsur + firefox 86.0**: no remote video + console error: `WebRTC: ICE failed, add a TURN server and see about:webrtc for more details`
- **m1air-bigsur + safari 14.0.3**: works! remote column gets video
(although the first window's source go black when you press start the second window - perhaps unable to share the camera between multiple windows, unlike the other browsers?)

---

pubsub example version: d1d74d4b303f247db20ad8c734f794260515735d

docker image version:
```
% docker images|head -n2
REPOSITORY                           TAG              IMAGE ID       CREATED             SIZE
pionwebrtc/ion-sfu                   latest-allrpc    be51ea104b37   45 hours ago        31.1MB
```

**Comment by tomsun** [comment]
Seems to work if you set nat1to1 to your LAN ip, i.e. here:
https://github.com/pion/ion-sfu/blob/312f56ff463fe7b81c6faa0dd2490646f9d532e5/config.toml#L66

Should the reader of [README.md](https://github.com/pion/ion-sfu/blob/master/examples/pubsubtest/README.md) be encouraged to do this?

(`image: pionwebrtc/ion-sfu:latest-allrpc` is potentially a bit of a black box ( https://github.com/pion/ion-sfu/issues/466 ) and can get out of sync with a given version of the README.md ( **latest-** allrpc from docker hub rather than a specific contract or a self-contained recipe provided with the repo - imagine if you clone the latest version and read the instructions 3 months later...), but... )

this approach seems to work at the time of writing:
```
  sfu:
    volumes:
      ../../config.toml:/configs/sfu.toml
    ...
```

**Comment by OrlandoCo** [comment]
@tomsun can you please confirm where are you deploying the SFU? if the SFU is not public accesible you need to set a STUN/TURN server, also make sure to open the UDP ports you set in the config file

**Comment by tomsun** [comment]
@OrlandoCo just trying to get the simplest possible example up n running on my local machine, pretending to be a newbie reading the docs for the first time... ;-)

I.e. I'm expecting https://github.com/pion/ion-sfu/tree/master/examples/pubsubtest#instructions to be complete - but I'm failing... and arguing that you might want to add nat1to1 to those instructions in most cases. true or not?

You could also run ion-sfu without docker, in which case you escape docker's internal nat... but the README suggests you use docker, so... hence this issue

**Comment by OrlandoCo** [comment]
@tomsun docker is not required for local testing the docuemtation also suggest to use the build command:

```go build ./cmd/signal/json-rpc/main.go && ./main -c config.toml``` 

You can replace with `run` for quick tests. With docker you can try setting the STUN servers from config

**Comment by tomsun** [comment]
@OrlandoCo yep I know you can do that - only pointing out that the example's README does not prescribe `go build` / `go run`, it only promotes `docker-compose up`, which I'm claiming doesn't work for the most part.

Guessing that it is asking you to use Docker as is a convenient way to get the example's `index.html` served through something other than `file://`, where WebRTC wouldn't work, nginx in this case. Although `python -m SimpleHTTPServer 8000` or something similar would work too, perhaps Docker is overkill.

Would be good if the author of the example would confirm whether they agree that `nat1to1` is required

**Comment by OrlandoCo** [comment]
`file://` works good for webrtc, what it does not work is serving from something different than localhost. Going to check the docker stuff.

**Comment by tomsun** [comment]
> file:// works
ok good! my bad: guess I'm applying my old `file://` is useless for development preconceptions too broadly then. yep, both ws://localhost and getting the camera viewfinder etc do indeed seem to work from `file://`, nice!

> Going to check the docker stuff
thanks!

**Comment by tarrencev** [comment]
@tomsun thank you for digging into this and providing feedback. documentation is definitely something we need to improve. any contributions to improving docs + simplifying the workflow would be greatly appreciated!

**Comment by adwpc** [comment]
pls try new version, free reopen
