### ISSUE TITLE
how to reproduce docker images published to `pionwebrtc/ion-sfu`?

### ISSUE THREAD

**Issue by tomsun** [pion/ion-sfu#466]
The Dockerfile in the repo root is not buildable currently; `sfu/` no longer exists:
https://github.com/pion/ion-sfu/blob/a2cee7424452f6f0eb2e61b803e29ef3582c8ebd/Dockerfile#L10
and it does not seem to define a `CMD` so not fully identical with the published ones anyway

https://hub.docker.com/r/pionwebrtc/ion-sfu/tags?page=1&ordering=last_updated publishes several variants (protoc, jsonrpc, allrpc) but does not link to any dockerfiles (in many official repos you can click a version and get to the corresponding Dockerfile snapshot on github.

**Comment by tomsun** [comment]
Motivation: Would like to change https://github.com/pion/ion-sfu/blob/d1d74d4b303f247db20ad8c734f794260515735d/examples/pubsubtest/docker-compose.yaml#L10-L11

locally to something along the lines of
```
  sfu:
    build: ../..
```

...and tweak and experiment from there, with the starting point being identical to what the example's README prescribes

**Comment by TannerGabriel** [comment]
The Dockerfiles used to build the images available on Dockerhub are not located in the repository's main directory. You can find the different Dockerfile in the following directories:

- json-rpc - `cmd/signal/json-rpc/Dockerfile`
- allrpc - `cmd/signal/allrpc/Dockerfile`
- grpc - `cmd/signal/grpc/Dockerfile`

**Comment by tomsun** [comment]
@TannerGabriel oh missed tham, perfect, thanks!
