### ISSUE TITLE
Bug on the latest version

### ISSUE THREAD

**Issue by edwinsyarief** [pion/ion-sfu#475]
### Your environment.
  - Version: latest from git
  - Client: 1.6.2
  - Environement: Windows 10
  - Are you using a TURN server? coturn
  - Other Information - I couldn't get the log, as I remember error sending binding track or something because too many chunks, and video become black and something sound is missing

### What did you do?
Change camera to screen and opposite

### What did you expect?
All participant able to see screen sharing and able to see camera, and try to mute and unmute

### What happened?
Screen become black, or sound missing

**Comment by adwpc** [comment]
pls try new version.
