### ISSUE TITLE
feat(sfu): add join config to signals

### ISSUE THREAD

**Issue by SnaiCrys** [pion/ion-sfu#483]
At the moment, it is not possible to use new configs (https://github.com/pion/ion-sfu/commit/54cd1c2d6132b0ba9ec4cf8a59b85f6013902015) with signal servers

**Comment by adwpc** [comment]
supported in sfu #529 
need https://github.com/pion/ion-sdk-js/issues/180

**Comment by adwpc** [comment]
Mark:https://github.com/pion/ion-sdk-go/pull/33
