### ISSUE TITLE
intermittent sfu crash when opening data channel immediately after joining

### ISSUE THREAD

**Issue by kcking** [pion/ion-sfu#523]
### Your environment.
  - Version: 1.9.8
  - Client: ion-sdk-js@1.6.4
  - Environment: EC2 ubuntu
  - Are you using a TURN server? no
  - Other Information - *stacktraces, webrtc dumps, related issues, suggestions how to fix, links for us to have context*

```
goroutine 1544322 [running]:
github.com/pion/ion-sfu/pkg/sfu.(*Session).AddDatachannel(0xc0000e4d00, 0xc000ba05a0, 0x24, 0xc0010b23c0)
        /home/ubuntu/ion-sfu/pkg/sfu/session.go:72 +0x10d
github.com/pion/ion-sfu/pkg/sfu.NewPublisher.func2(0xc0010b23c0)
        /home/ubuntu/ion-sfu/pkg/sfu/publisher.go:110 +0x9d
github.com/pion/webrtc/v3.(*API).NewPeerConnection.func1(0xc0010b23c0)
        /root/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.20/peerconnection.go:174 +0x6a
github.com/pion/webrtc/v3.(*SCTPTransport).onDataChannel.func1(0xc001378eb0, 0xc0010b23c0, 0xc001064230)
        /root/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.20/sctptransport.go:269 +0x30
created by github.com/pion/webrtc/v3.(*SCTPTransport).onDataChannel
        /root/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.20/sctptransport.go:268 +0x136
exit status 2
```

### What did you do?
ion-sdk-js clients join sfu session and immediately open a data channel to exchange additional information

### What did you expect?
no crash ❤️ 
### What happened?
crash with above strack trace occurs every couple of days in our internal testing

**Comment by OrlandoCo** [comment]
Hey @kcking can you share the reason of the crash if it was a nil dereference? 

Also when you open the datachannel you mean after client join call??  if so you should wait until publisher PC is ready

**Comment by kcking** [comment]
Thank you for the quick response! The crash happens on this line

```
	s.peers[owner].subscriber.channels[label] = dc
```
I imagine because the `peers[owner]` or subscriber is nil?

Our client code looks like

```
    this.signal.onopen = () => {
      this.client.join(params.roomID, this.uid);
      this.streamInfoDataChannel = this.client.createDataChannel(
        "stream-types"
      );
      ...
```

Would you instead recommend that we await the `client.join()` before creating a data channel? In either case, it feels like the crash of the sfu should be avoided somehow to prevent DoS.

**Comment by OrlandoCo** [comment]
@kcking yeah, the issue is that the DC is created before the peer is fully negotiated. And you are right we should prevent it. 

Atm if you want to fix it, join returns a promise, I suggest to create the DC once the promise is resolved.

**Comment by manishiitg** [comment]
i think something like 
```
await this.client.join
```

would work
