### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by adwpc** [pion/ion-sfu#528]
panic: send on closed channel

goroutine 9727 [running]:
github.com/gammazero/workerpool.(*WorkerPool).Submit(...)
	/root/go/pkg/mod/github.com/gammazero/workerpool@v1.1.2/workerpool.go:109
github.com/pion/ion-sfu/pkg/sfu.(*WebRTCReceiver).RetransmitPackets(0xc001339200, 0xc005a16000, 0xc002e02b20, 0x1, 0x1, 0xc002e02b20, 0x0)
	/root/ion-sfu/pkg/sfu/receiver.go:281 +0xdf
github.com/pion/ion-sfu/pkg/sfu.(*DownTrack).handleRTCP(0xc005a16000, 0xc0045e4000, 0x10, 0x2000)
	/root/ion-sfu/pkg/sfu/downtrack.go:537 +0x798
github.com/pion/ion-sfu/pkg/sfu.(*DownTrack).Bind.func1(0xc0045e4000, 0x10, 0x2000)
	/root/ion-sfu/pkg/sfu/downtrack.go:101 +0x48
github.com/pion/ion-sfu/pkg/buffer.(*RTCPReader).Write(0xc00372fd60, 0xc0045e4000, 0x10, 0x2000, 0xc00790db20, 0x0, 0x0)
	/root/ion-sfu/pkg/buffer/rtcpreader.go:25 +0xa2
github.com/pion/srtp/v2.(*ReadStreamSRTCP).write(0xc0

**Comment by adwpc** [comment]
scene: benchmarking by ion-sfu-load-tool

**Comment by OrlandoCo** [comment]
mmm this is weird since the worker checks if its closed before submit
