### ISSUE TITLE
Late joiner will get black screen when the host switched to share screen

### ISSUE THREAD

**Issue by edwinsyarief** [pion/ion-sfu#536]
### Your environment.
  - Version: GIT
  - Client: 1.7.2
  - Environment: Windows
  - Are you using a TURN server? Coturn
  - Other Information - There is no error. Just get black screen.

### What did you do?
- The host start the stream
- participants joined the room. (participants still able to see the host video)
- The host switch video to share screen
- more participants joined the room. (the previous participants which already joined before share screen started still able to see the host, but the late joiner or join after the host share screen only able to see black screen.

### What did you expect?
The participants must be able to see the host's screen even when late join.

### What happened?
The participant see the black screen

![image](https://user-images.githubusercontent.com/13018338/120660420-82581c00-c4b1-11eb-9d34-ddca607c825f.png)

**Comment by billylindeman** [comment]
Your issue may be related to this fix https://github.com/pion/ion-sfu/commit/7ecf8fbe03a4ef257d53f802f4d765787a7dd4b4. can you please test again on master and verify.

**Comment by edwinsyarief** [comment]
Okay, will test, thank you

**Comment by edwinsyarief** [comment]
Hi Sorry for the late reply.

This issue is fixed. Thank you.

Best Regards,
Edwin
