### ISSUE TITLE
ion-sfu crash on Switching to QHD stream with SimulCast Enabled

### ISSUE THREAD

**Issue by buriedgod** [pion/ion-sfu#541]
### Your environment.
  - Version: *1.9.8*
  - Client: *1.6.2*
  - Environement: *Docker*
  - Are you using a TURN server? *pion turn*
  - Other Information - *n v=0
[2021-06-11 06:58:52.422] [INFO] [peer.go:116] => Send offer peer_id=[REDACTED]/ckojolsmw00310125n3sr9s4f/[REDACTED]-linux-chrome-nl v=0
[2021-06-11 06:58:52.560] [INFO] [peer.go:204] => Peer got answer peer_id=[REDACTED]/ckojola4800300125k41exmsi/[REDACTED] v=0
[2021-06-11 06:58:52.573] [INFO] [peer.go:204] => Peer got answer peer_id=[REDACTED]/ckojolsmw00310125n3sr9s4f/[REDACTED]-linux-chrome-nl v=0
panic: runtime error: index out of range [2] with length 0

goroutine 75961 [running]:
github.com/pion/ion-sfu/pkg/sfu.modifyVP8TemporalPayload(...)
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.8/pkg/sfu/helpers.go:72
github.com/pion/ion-sfu/pkg/sfu.setVP8TemporalLayer(0xc0014828f0, 0xc0012ef6c0, 0x0, 0x0, 0x0, 0x1000000)
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.8/pkg/sfu/helpers.go:64 +0x314
github.com/pion/ion-sfu/pkg/sfu.(*DownTrack).writeSimulcastRTP(0xc0012ef6c0, 0xc0014828f0, 0x0, 0x0)
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.8/pkg/sfu/downtrack.go:400 +0x5e7
github.com/pion/ion-sfu/pkg/sfu.(*DownTrack).WriteRTP(0xc0012ef6c0, 0xc0014828f0, 0x0, 0x0)
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.8/pkg/sfu/downtrack.go:157 +0x65
github.com/pion/ion-sfu/pkg/sfu.(*WebRTCReceiver).writeRTP(0xc000d2ec00, 0x2)
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.8/pkg/sfu/receiver.go:357 +0x1c8
created by github.com/pion/ion-sfu/pkg/sfu.(*WebRTCReceiver).AddUpTrack
	/go/pkg/mod/github.com/pion/ion-sfu@v1.9.8/pkg/sfu/receiver.go:163 +0x22b*

### What did you do?
Using ion-sfu with simulcast enabled and then tried upgrading the resolution of the stream to QHD

### What did you expect?
ion-sfu continues to work smoothly

### What happened?
ion-sfu crashed

**Comment by adwpc** [comment]
pls try new version.
