### ISSUE TITLE
simulcast support

### ISSUE THREAD

**Issue by tarrencev** [pion/ion-sfu#57]
integrate pion simulcast

- [ ] Update remb loop to add bw state to sender
- [ ] sscrc/rid/quality map exposed to sender
- [ ] Router forwards all simulcast packets to sender (may be no change)
- [ ] Sender inspects simulcast packet and forwards packets for stream best matching current sender bw
- [ ] Make sure client is sending abs-time extensions. (required for correct remb)
- [ ] Configure abs-time extension in offers

**Comment by jinleileiking** [comment]
I am interested in this issue. But do not know how to do.
