### ISSUE TITLE
memory leak doubted

### ISSUE THREAD

**Issue by lenaky** [pion/ion-sfu#570]
### Your environment.
  - Version: v1.10.6
  - Client: v1.10.6 pubsubtest example 
  - Environement: mac osx big sur 11.5.1
  - Are you using a TURN server? no
  - Other Information - `config.toml` ballast set to 0

### What did you do?

opened chrome about 6~7 tab and connected pubsubtest page with `publisher`. 
I kept clicking refresh button many times for 10 minutes on last tab.
after 20minutes, I did exactly same thing before.

### What did you expect?

after all connection is closed and gc runs, RES of `top` should not extend. 

### What happened?

RES keep increasing. `go tool pprof /heap` shows some func's `flat` and `cum` is increasing too. 
ex ) 
`flat  flat%   sum%        cum   cum%`
` 2099.89kB  5.16% 46.90%  3123.98kB  7.68%  github.com/pion/webrtc/v3.(*PeerConnection).CreateOffer`
` 512.14kB  1.26% 81.13%  5633.26kB 13.84%  github.com/pion/webrtc/v3.(*PeerConnection).SetLocalDescription` 
=>
`flat  flat%   sum%        cum   cum%`
`2.56MB  3.26% 46.93%     4.56MB  5.81%  github.com/pion/webrtc/v3.(*PeerConnection).CreateOffer`
`1MB  1.28% 11.48%       13MB 16.58%  github.com/pion/webrtc/v3.(*PeerConnection).SetLocalDescription`

**Comment by OrlandoCo** [comment]
Is weird that mems keeps increasing on CreateOffer and SetLocalDescription,  can you share a quick gist to simulate the same behavior?

**Comment by lenaky** [comment]
I guess, establishing json-rpc connection and sending `join` operation repeatedly can simulate this behavior. I will try.

**Comment by lenaky** [comment]
sorry I'm rate. #580 is the reason why this is happening. To test, I simply added  `time.Time` in `buffer.RTCPReader` to store time.Now() when `Write()` calls. then `factory.GetOrNew()`'s goroutine that checks readers is not working removes from `f.rtcpReaders`. now I can't find any leak.
