### ISSUE TITLE
Offered Ignored error when using docker-image because peerconnection was closed.

### ISSUE THREAD

**Issue by miseifert** [pion/ion-sfu#571]
### Your environment.
  - Version: current master of ion-sfu: d7b670b037fb01d4860686023a757d36cf434357
  - Client: current master of ion-sdk-js: v1.5.5 and v1.7.2 (didn't test others)
  - Environment: docker (localhost and server)
  - Are you using a TURN server? no

### What did you do?

I build the docker image for the JSON-rpc:

```
docker build -f cmd/signal/json-rpc/Dockerfile -t my-ion-sfu:0.0.1 .
docker run -p 7000:7000 -p 5000-5200:5000-5200/udp  my-ion-sfu:0.0.1
```

When I then try to send a video over this SFU (e.g. using https://github.com/pion/ion-sfu/tree/master/examples/pubsubtest with my custom docker image) I get an `offered ignored` error (https://github.com/pion/ion-sfu/blob/aa273c96ed18c362ebe0f4e7cfe5f840f2f98234/pkg/sfu/peer.go#L24). I don't have much experience with go but I found out that the signaling state at that point was "closed" and therefor I got the error. However I couldn't figure out why it closed the peer-connections.

When I just compile the json-rpc using go (no docker) it works without problems.

Sorry, I am a bit short of time and don't exactly know what other Information could be useful. Please let me know if I can provide more context to this issue. :)

**Comment by faizul123** [comment]
Same issues happening when I setup docker on aws ec2 instance.

**Comment by adwpc** [comment]
pls try new version.

**Comment by diazoxide** [comment]
Still actual. I'm trying on my server. Only working on local docker setup. All remote connections receiving 

`{code: 500, message: 'offered ignored', data: null}`

**Comment by leica19** [comment]
i also have the same issue on gcp platforms..
