### ISSUE TITLE
 session.go AddDatachannel function deadlock  line 166

### ISSUE THREAD

**Issue by 435420057** [pion/ion-sfu#582]
`func (s *SessionLocal) AddDatachannel(owner string, dc *webrtc.DataChannel) {
	label := dc.Label()

	s.mu.Lock()
	for _, lbl := range s.fanOutDCs {
		if label == lbl {
                        //   **deadlock** 
			return  
		}
	}
	s.fanOutDCs = append(s.fanOutDCs, label)
	peerOwner := s.peers[owner]
	s.mu.Unlock()`

**Comment by OrlandoCo** [comment]
Good catch, than you! will fix asap

**Comment by OrlandoCo** [comment]
fixed now ty!
