### ISSUE TITLE
Data race

### ISSUE THREAD

**Issue by 435420057** [pion/ion-sfu#587]
### Your environment.
  - Version: *master*

### What happened?
在 pkg/buffer/buffer.go 文件中有三个变量存竞争问题分别是：
lastSRRTPTime 
lastSRNTPTime 
lastSRRecv

在函数 SetSenderReportData中使用锁(sync.Mutex)定后，批量设置这三个变量，但是在其它地方使用的时候
却使用 sync/atomic 读取数据，这样造成锁无效，他并不是同一个锁。所以造成data race

`func (b *Buffer) SetSenderReportData(rtpTime uint32, ntpTime uint64) {

	b.Lock()  // **sync.Mutex  Different locks**

	b.lastSRRTPTime = rtpTime   

	b.lastSRNTPTime = ntpTime 

	b.lastSRRecv = time.Now().UnixNano()

	b.Unlock()

}

func (b *Buffer) GetSenderReportData() (rtpTime uint32, ntpTime uint64, lastReceivedTimeInNanosSinceEpoch int64) {

	rtpTime = atomic.LoadUint32(&b.lastSRRTPTime)  // **sync/atomic Different locks**

	ntpTime = atomic.LoadUint64(&b.lastSRNTPTime) // **sync/atomic Different locks**

	lastReceivedTimeInNanosSinceEpoch = atomic.LoadInt64(&b.lastSRRecv) // **sync/atomic Different locks**

	return rtpTime, ntpTime, lastReceivedTimeInNanosSinceEpoch
}`

两个不锁造成数据读取时产生竞争

**Comment by adwpc** [comment]
@435420057 Good Catch！Fell free to PR if you like!
