### ISSUE TITLE
scalability solutions documentation

### ISSUE THREAD

**Issue by mohammadne** [pion/ion-sfu#607]
HI @Sean-Der 

## Summary

I think one of the challenges for people using `ion-sfu` and other media-servers would be
the challenge of `scalability` and `load balancing`

in my case I want to use [EMQX](https://www.emqx.io/) as broker responsible for signaling among peers
and I really stick that how we should scale a custom version of ion ( very similar to `json-rpc` which uses `EMQX` )

## Motivation

I think it's a common challenge for all want to use `ion-sfu` 

## Describe alternatives you've considered

currently no Idea.

**Comment by adwpc** [comment]
Maybe you can develop a `EMQX` signal layer which like `grpc|jsonrpc` in https://github.com/pion/ion-sfu/tree/master/cmd/signal
