### ISSUE TITLE
How many users can join to the conference?

### ISSUE THREAD

**Issue by A2DNEW** [pion/ion-sfu#615]
Hi
I use `ion-sfu` and it work good for 4 users.
I want use video conference for 15 users in 1 conference.
Before `ion-sfu`, I use `peerjs` and this library crashing for 6 users.
My server:
8gig ram
2 vCore cpu

**Comment by adwpc** [comment]
support 50 people in one room on Google GCE(4Core 3.2GHZ)
do not use shared cpu

**Comment by PruthvinathR** [comment]
@adwpc Is 50 clients a limitation on sfu? Can I have multiple rooms with 50 people each?
