### ISSUE TITLE
Where do we set the TURN server address when we run ion sfu on the server

### ISSUE THREAD

**Issue by PruthvinathR** [pion/ion-sfu#616]
I found out that my server is behind symetric NAT and my client is behind a normal NAT and hence the connection fails when trying to connect over the internet. In order to overcome this issue I've deployed my own TURN server and I pass the TURN server config to the client and it still doesn't fix my issue. Should I also give the TURN server address to the SFU server running on the remote server? If so how can I do that? I'm currently running the following command to run SFU. 

docker run -p 50051:50051 -p 5000-5200:5000-5200/udp pionwebrtc/ion-sfu:latest-grpc

**Comment by adwpc** [comment]
set turn server in sfu.toml
