### ISSUE TITLE
subscribe as needed

### ISSUE THREAD

**Issue by adwpc** [pion/ion-sfu#62]
There is a scene like this:
With 50 people in one room, it is impossible to subscribe to all of them on the mobile.
modile can only decode several streams.

**Comment by tarrencev** [comment]
i think this will be solved with the simulcast support. for simulcast, i would like the client to be able to request different video resolutions over a data channel (depending on layout, ect). one of those could be no video/no audio. so the tracks would still be sub'd but in a suspended state
