### ISSUE TITLE
improve api suggestion

### ISSUE THREAD

**Issue by adwpc** [pion/ion-sfu#63]
I learned the code, really cool! simple and powful!

Some suggestion:
* Room=>Session ?
(one peer can join two different sessions)

* Peer=>WebRTCTransport ? 
(peer derived from transport, there can by many transport: QUICTransport RTPTransport etc..)

* VideoReceiver => VideoTrackReceiver or WebRTCVideoReceiver? 
* AudioReceiver => AudioTrackReceiver or WebRTCAudioReceiver?

**Comment by adwpc** [comment]
@tarrencev @jbrady42 
if you agree , i can do a quick replace after you merged your code.

**Comment by tarrencev** [comment]
i like these all. I think `VideoTrackReceiver` and `AudioTrackReceiver` makes most sense (since same sender/receiver could be used for other transports)

**Comment by tarrencev** [comment]
@adwpc i've taken care of session + webrtctransport
