### ISSUE TITLE
ion-sfu update offer to client. but the offer is longer and longer as the participant come and leave

### ISSUE THREAD

**Issue by r1a2y3** [pion/ion-sfu#635]
1. start ion-sfu server. 
```
go build ./cmd/signal/json-rpc/main.go && ./main -c config.toml
```
2. disable video and enable audio in examples/pubsubtest/main.js to publish and subscribe audio
3. open twice index.html. one publish and one subscribe. and the subscriber will receive offer from ion-sfu
4. open more and more pages and publish audio. the subscriber receives more and more mediaSection in offer
5. close those publisher one by one. the subscriber receieves offers but the count of mediaSection don't decrease, but those closed with a=inactive.    
<img width="765" alt="inactive-issues" src="https://user-images.githubusercontent.com/29532860/148221083-d256e80f-ee83-4e57-bea8-b937fa32cf7d.png">

**Comment by OrlandoCo** [comment]
Hello @r1a2y3, thats the default behavior of webrtc, before we have experimented with recycling transceivers, but different browsers behaved different causing issues.

So besides the fact that you are getting big SDP there is no other side effect.

**Comment by r1a2y3** [comment]
Hello @OrlandoCo ,thanks for your patient answer.
btw, I experimented with Google Meet. It won't get a big SDP while participants come and leave. So I think there may have a solution to  resolve it.
In a larger meeting. the big SDP may have tens of thousands lines, it's Intolerable and inconvenient to log out and troubleshoot.
