### ISSUE TITLE
Question: Why are no codecs registered when creating a Subscriber?

### ISSUE THREAD

**Issue by GRVYDEV** [pion/ion-sfu#648]
Hey all, Ive been playing around with Ion and ran into an issue where the offer generated by the server for a subscriber was not valid on Safari. After doing some poking around i realized no codecs are registered for the [subscriber media engine](https://github.com/pion/ion-sfu/blob/d1c505133a34ad3e16c820b8bc521c580801ba71/pkg/sfu/mediaengine.go#L89-L92) when it's created. I'm curious why this is the case.

I was able to solve my problem by registering default codecs here https://github.com/pion/ion-sfu/blob/d1c505133a34ad3e16c820b8bc521c580801ba71/pkg/sfu/subscriber.go#L35-L39

**Comment by GRVYDEV** [comment]
My thought around this is that you only want to register client supported codecs on the subscriber side?

**Comment by OrlandoCo** [comment]
This is strange, subscribers does not register codecs because it registers the codec send by other publishers:

https://github.com/pion/ion-sfu/blob/d1c505133a34ad3e16c820b8bc521c580801ba71/pkg/sfu/router.go#L247

Maybe the issue is that publisher codec was not supported by Safari?

**Comment by GRVYDEV** [comment]
After taking a brief look it seems that this registers the codec that the media is currently being sent on. Wouldn't it make more sense to register all the codecs that the publisher is capable of sending?

**Comment by OrlandoCo** [comment]
SFU will not transcode, and and the moment will not renegotiate codecs in case is not compatible, if we do this, if Chrome publish VP9, Safari will try to select Vp8 or H264 supported codecs, which will not make sense since stream is VP9.

**Comment by GRVYDEV** [comment]
> SFU will not transcode, and and the moment will not renegotiate codecs in case is not compatible, if we do this, if Chrome publish VP9, Safari will try to select Vp8 or H264 supported codecs, which will not make sense since stream is VP9.

Got it, after doing some SDP research and getting a better idea of how negotiating codecs works I figured out what we need to do. Thank you!
