### ISSUE TITLE
name of media engines are uppercase in pion/webrtc but are lowercase in pion/ion-sfu

### ISSUE THREAD

**Issue by yindaheng98** [pion/ion-sfu#661]
### Your environment.
  - Version: *68545cc25230220435ee028d5a0af6e768a0a79a*
  - Client: *github.com/pion/webrtc*
  - Environement: *Docker*
  - Are you using a TURN server? *no*
  - Other Information - *stacktraces, webrtc dumps, related issues, suggestions how to fix, links for us to have context*

### What did you do?

Try to connect to SFU with a webrtc.Peerconnection, like [example code here](https://github.com/pion/webrtc/blob/master/examples/play-from-disk/main.go#L60)

### What did you expect?

It should connect

### What happened?

**Unsupported media engine**

### Cause

I found that the name of media engines in pion/ion-sfu is **lowercase**: [code here](https://github.com/pion/ion-sfu/blob/68545cc25230220435ee028d5a0af6e768a0a79a/pkg/sfu/mediaengine.go#L8)

In pion/webrtc however, name of media engines is **uppercase**: [code here](https://github.com/pion/webrtc/blob/master/mediaengine.go#L19)

So when I use the code like the example in pion/webrtc, it doesn't work

Also I found the test code in pion/ion-sfu is not the same as the example in pion/webrtc: [test code here](https://github.com/pion/ion-sfu/blob/68545cc25230220435ee028d5a0af6e768a0a79a/pkg/sfu/sfu_test.go#L112) and [example code here](https://github.com/pion/webrtc/blob/master/examples/play-from-disk/main.go#L60)

It is not a serious bug but takes me several hours. So why not use the same case?

**Comment by ojroques** [comment]
I ran into the same issue. There must be an issue with the way the SDP is parsed as pion/webrtc explicitly states that "Matching should be case insensitive."

https://github.com/pion/webrtc/blob/42dc0d47883bb32266325502f3e052ff9afb3f78/mediaengine.go#L21
