### ISSUE TITLE
move renegotiation to data channel

### ISSUE THREAD

**Issue by tarrencev** [pion/ion-sfu#67]
we could do renegotiation in a data channel. then the only out-of-band signaling we would need is the initial exchange

**Comment by tarrencev** [comment]
i think this might actually be undesirable, since it means the signaling layer cant enforce sdp constraints

**Comment by adwpc** [comment]
@tarrencev Agree. We can use singal layer(grpc/jsonrpc) for renegotiation. datachannel can be used for future feature, like: file sharing.
